version: '3.7'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ttl_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        container_name: mysql_container
